corpora:
  german:
    - 20min
  #   # - cs_de
  #   # - ggponc
    - pubmed_de
    # - zora_de
  english:
    - cnn
    # - e3c
    # - zora_en
    - pubmed_en
    # - cs_en

domains:
  science:
    - pubmed_en
    - pubmed_de
    # - zora_en
    # - zora_de
  news:
    - cnn
    - 20min
    # - cs_en
    # - cs_de
  # clinical:
    # - e3c
    # - ggponc

tasks:
  - human
  # - continue
  # - explain
  # - create
  - ashuman
  - asmachine