
features_custom = [
    "connectives",
    "connectives_cap",
    "shannon_entropy",
    "simpson_diversity"
]

features_to_visualize_dict = {
    # information_theory
    "entropy": "inf entropy",
    "perplexity": "inf perplexity",
    "per_word_perplexity": "inf perplexity per word",
    # descriptive_stats
    "token_length_mean": "des token length mean",
    "token_length_median": "des token length median",
    "token_length_std": "des token length std",
    "sentence_length_mean": "des sent length mean",
    "sentence_length_median": "des sent length median",
    "sentence_length_std": "des sent length std",
    "syllables_per_token_mean": "des syllabs per token mean",
    "syllables_per_token_median": "des syllabs per token median",
    "syllables_per_token_std": "des syllabs per token std",
    "n_tokens": "des num of tokens",
    "n_unique_tokens": "des num of unique tokens",
    "proportion_unique_tokens": "des prop unique tokens",
    "n_characters": "des num of chars",
    "n_sentences": "des num of sents",
    # quality
    "n_stop_words": "des num of stop words",
    "alpha_ratio": "qua  alpha ratio",
    "mean_word_length": "qua  mean word length",
    "doc_length": "des doc length",
    "symbol_to_word_ratio_#": "qua  symbol to word ratio #",
    "proportion_ellipsis": "qua  prop ellipsis",
    "proportion_bullet_points": "qua  prop bullet points",
    "duplicate_line_chr_fraction": "qua  dupl line chr fract",
    "duplicate_paragraph_chr_fraction": "qua  dupl para chr fract",
    "duplicate_ngram_chr_fraction_5": "qua  dupl ngram chr fract 5",
    "duplicate_ngram_chr_fraction_6": "qua  dupl ngram chr fract 6",
    "duplicate_ngram_chr_fraction_7": "qua  dupl ngram chr fract 7",
    "duplicate_ngram_chr_fraction_8": "qua  dupl ngram chr fract 8",
    "duplicate_ngram_chr_fraction_9": "qua  dupl ngram chr fract 9",
    "duplicate_ngram_chr_fraction_10": "qua  dupl ngram chr fract 10",
    "top_ngram_chr_fraction_2": "qua  top ngram chr fract 2",
    "top_ngram_chr_fraction_3": "qua  top ngram chr fract 3",
    "top_ngram_chr_fraction_4": "qua  top ngram chr fract 4",
    "oov_ratio": "qua  oov ratio",
    # dependency_distance
    "dependency_distance_mean": "dep distance mean",
    "dependency_distance_std": "dep distance std",
    "prop_adjacent_dependency_relation_mean": "dep prop adj rel mean",
    "prop_adjacent_dependency_relation_std": "dep prop adj rel std",
    # Readability
    "flesch_reading_ease": "red  flesch reading ease",
    "flesch_kincaid_grade": "red  flesch kincaid grade",
    "gunning_fog": "red  gunning fog",
    "automated_readability_index": "red  autom readability index",
    "coleman_liau_index": "red  coleman liau index",
    "lix": "red  LIX",
    "rix": "red  RIX",
    # POS
    "pos_prop_ADJ": "pos prop of adjectives",
    "pos_prop_ADP": "pos prop of adpositions",
    "pos_prop_ADV": "pos prop of adverbs",
    "pos_prop_CCONJ": "pos prop of coord conjunctions",
    "pos_prop_DET": "pos prop of determiners",
    "pos_prop_NOUN": "pos prop of nouns",
    "pos_prop_NUM": "pos prop of numerals",
    "pos_prop_PART": "pos prop of particles",
    "pos_prop_PRON": "pos prop of pronouns",
    "pos_prop_PROPN": "pos prop of proper nouns",
    "pos_prop_PUNCT": "pos prop of punctuation",
    "pos_prop_SPACE": "pos prop of space",
    "pos_prop_SYM": "pos prop of symbols",
    "pos_prop_VERB": "pos prop of verbs",
    "pos_prop_X": "pos prop X",
    "pos_prop_AUX": "pos prop of auxiliaries",
    "pos_prop_SCONJ": "pos prop of subord conjunctions",
    # coherence
    "first_order_coherence": "coh 1st order coherence",
    "second_order_coherence": "coh 2nd order coherence",
    "connectives": "coh connectives",
    "connectives_cap": "coh connectives capitalised",
    # morphology
    "shannon_entropy": "mor shannon entropy",
    "simpson_diversity": "mor simpson diversity",
    # lexical diversity
    "mtld": "led MTLD",
    "type_token_ratio": "led TTR",
    "yules_k": "led Yule's K",
    "yules": "led Yule's K",
}

features_raw_counts = [
    "connectives",
    "connectives_cap",
    "n_tokens",
    "n_unique_tokens",
    "n_characters",
    "n_sentences",
    "n_stop_words",
    "doc_length",
]

features_list = [
    # information_theory
    "entropy", 
    "perplexity",
    "per_word_perplexity",

    # descriptive_stats
    "token_length_mean",
    "token_length_median",
    "token_length_std",
    "sentence_length_mean",
    "sentence_length_median",
    "sentence_length_std",
    "syllables_per_token_mean",
    "syllables_per_token_median",
    "syllables_per_token_std",
    "n_tokens",
    "n_unique_tokens",
    "proportion_unique_tokens",
    "n_characters",
    "n_sentences",

    # quality
    # "passed_quality_check",
    "n_stop_words", 
    "alpha_ratio",
    "mean_word_length",
    "doc_length",
    "symbol_to_word_ratio_#",
    "proportion_ellipsis",
    "proportion_bullet_points",
    # "contains_lorem ipsum",
    "duplicate_line_chr_fraction",
    "duplicate_paragraph_chr_fraction",
    "duplicate_ngram_chr_fraction_5",
    "duplicate_ngram_chr_fraction_6",
    "duplicate_ngram_chr_fraction_7",
    "duplicate_ngram_chr_fraction_8",
    "duplicate_ngram_chr_fraction_9",
    "duplicate_ngram_chr_fraction_10",
    "top_ngram_chr_fraction_2",
    "top_ngram_chr_fraction_3",
    "top_ngram_chr_fraction_4",
    "oov_ratio",

    # dependency_distance
    "dependency_distance_mean",
    "dependency_distance_std",
    "prop_adjacent_dependency_relation_mean",
    "prop_adjacent_dependency_relation_std",

    # Readability
    "flesch_reading_ease",
    "flesch_kincaid_grade",
    "gunning_fog",
    "automated_readability_index",
    "coleman_liau_index",
    "lix",
    "rix"

    # POS
    "pos_prop_ADJ",
    "pos_prop_ADP",
    "pos_prop_ADV",
    "pos_prop_CCONJ",
    "pos_prop_DET",
    "pos_prop_NOUN",
    "pos_prop_NUM",
    "pos_prop_PART",
    "pos_prop_PRON",
    "pos_prop_PROPN",
    "pos_prop_PUNCT",
    "pos_prop_SPACE",
    "pos_prop_SYM",
    "pos_prop_VERB",
    "pos_prop_X",
    "pos_prop_AUX",
    "pos_prop_SCONJ",

    # coherence
    "first_order_coherence",
    "second_order_coherence",
]
