features_list = [
    # information_theory
    "entropy", 
    "perplexity",
    "per_word_perplexity",

    # descriptive_stats
    "token_length_mean",
    "token_length_median",
    "token_length_std",
    "sentence_length_mean",
    "sentence_length_median",
    "sentence_length_std",
    "syllables_per_token_mean",
    "syllables_per_token_median",
    "syllables_per_token_std",
    "n_tokens",
    "n_unique_tokens",
    "proportion_unique_tokens",
    "n_characters",
    "n_sentences",

    # quality
    # "passed_quality_check",
    "n_stop_words", 
    "alpha_ratio",
    "mean_word_length",
    "doc_length",
    "symbol_to_word_ratio_#",
    "proportion_ellipsis",
    "proportion_bullet_points",
    # "contains_lorem ipsum",
    "duplicate_line_chr_fraction",
    "duplicate_paragraph_chr_fraction",
    "duplicate_ngram_chr_fraction_5",
    "duplicate_ngram_chr_fraction_6",
    "duplicate_ngram_chr_fraction_7",
    "duplicate_ngram_chr_fraction_8",
    "duplicate_ngram_chr_fraction_9",
    "duplicate_ngram_chr_fraction_10",
    "top_ngram_chr_fraction_2",
    "top_ngram_chr_fraction_3",
    "top_ngram_chr_fraction_4",
    "oov_ratio",

    # dependency_distance
    "dependency_distance_mean",
    "dependency_distance_std",
    "prop_adjacent_dependency_relation_mean",
    "prop_adjacent_dependency_relation_std",

    # Readability
    "flesch_reading_ease",
    "flesch_kincaid_grade",
    "gunning_fog",
    "automated_readability_index",
    "coleman_liau_index",
    "lix",
    "rix"

    # POS
    "pos_prop_ADJ",
    "pos_prop_ADP",
    "pos_prop_ADV",
    "pos_prop_CCONJ",
    "pos_prop_DET",
    "pos_prop_NOUN",
    "pos_prop_NUM",
    "pos_prop_PART",
    "pos_prop_PRON",
    "pos_prop_PROPN",
    "pos_prop_PUNCT",
    "pos_prop_SPACE",
    "pos_prop_SYM",
    "pos_prop_VERB",
    "pos_prop_X",
    "pos_prop_AUX",
    "pos_prop_SCONJ",

    # coherence
    "first_order_coherence",
    "second_order_coherence",
]

features_custom = [
    "connectives",
    "connectives_cap",
    "shannon_entropy",
    "simpson_diversity"
]

features_to_visualize_dict = {
    "entropy": "entropy",
    "perplexity": "perplexity",
    "per_word_perplexity": "perplexity per word",
    "token_length_mean": "token len mean",
    "token_length_median": "token len median",
    "token_length_std": "token len std",
    "sentence_length_mean": "sent len mean",
    "sentence_length_median": "sent len median",
    "sentence_length_std": "sent len std",
    "syllables_per_token_mean": "syllabs/token_mean",
    "syllables_per_token_median": "syllabs/token_median",
    "syllables_per_token_std": "syllabs/token_std",
    "n_tokens": "num tokens",
    "n_unique_tokens": "num unique tokens",
    "proportion_unique_tokens": "prop unique tokens",
    "n_characters": "num chars",
    "n_sentences": "num sents",
    "n_stop_words": "num stop words",
    "alpha_ratio": "alpha ratio",
    "mean_word_length": "mean word len",
    "doc_length": "doc len",
    "symbol_to_word_ratio_#": "symbol/word ratio #",
    "proportion_ellipsis": "prop ellipsis",
    "proportion_bullet_points": "prop bullet points",
    "duplicate_line_chr_fraction": "dupl line chr fract",
    "duplicate_paragraph_chr_fraction": "dupl para chr fract",
    "duplicate_ngram_chr_fraction_5": "dupl ngram chr fract 5",
    "duplicate_ngram_chr_fraction_6": "dupl ngram chr fract 6",
    "duplicate_ngram_chr_fraction_7": "dupl ngram chr fract 7",
    "duplicate_ngram_chr_fraction_8": "dupl ngram chr fract 8",
    "duplicate_ngram_chr_fraction_9": "dupl ngram chr fract 9",
    "duplicate_ngram_chr_fraction_10": "dupl ngram chr fract 10",
    "top_ngram_chr_fraction_2": "top ngram chr fract 2",
    "top_ngram_chr_fraction_3": "top ngram chr fract 3",
    "top_ngram_chr_fraction_4": "top ngram chr fract 4",
    "oov_ratio": "oov ratio",
    "dependency_distance_mean": "dep distance mean",
    "dependency_distance_std": "dep distance std",
    "prop_adjacent_dependency_relation_mean": "prop adj dep rel mean",
    "prop_adjacent_dependency_relation_std": "prop adj dep rel std",
    "flesch_reading_ease": "flesch reading ease",
    "flesch_kincaid_grade": "flesch kincaid grade",
    "gunning_fog": "gunning fog",
    "automated_readability_index": "autom readability index",
    "coleman_liau_index": "coleman liau index",
    "lix": "lix",
    "rix": "rix",
    "pos_prop_ADJ": "prop ADJ",
    "pos_prop_ADP": "prop ADP",
    "pos_prop_ADV": "prop ADV",
    "pos_prop_CCONJ": "prop CCONJ",
    "pos_prop_DET": "prop DET",
    "pos_prop_NOUN": "prop NOUN",
    "pos_prop_NUM": "prop NUM",
    "pos_prop_PART": "prop PART",
    "pos_prop_PRON": "prop PRON",
    "pos_prop_PROPN": "prop PROPN",
    "pos_prop_PUNCT": "prop PUNCT",
    "pos_prop_SPACE": "prop SPACE",
    "pos_prop_SYM": "prop SYM",
    "pos_prop_VERB": "prop VERB",
    "pos_prop_X": "prop X",
    "pos_prop_AUX": "prop AUX",
    "pos_prop_SCONJ": "prop SCONJ",
    "first_order_coherence": "1st order coherence",
    "second_order_coherence": "2nd order coherence",
    "connectives": "connectives",
    "connectives_cap": "connectives_cap",
    "shannon_entropy": "shannon",
    "simpson_diversity": "simpson",
    "mtld": "mtld",
    "type_token_ratio": "TTR",
    "yules_k": "Yule's K",

}

features_raw_counts = [
    "connectives",
    "connectives_cap",
    "n_tokens",
    "n_unique_tokens",
    "n_characters",
    "n_sentences",
    "n_stop_words",
    "doc_length",
]

