features_list = [
    # information_theory
    "entropy",
    "perplexity",
    "per_word_perplexity",

    # descriptive_stats
    "token_length_mean",
    "token_length_median",
    "token_length_std",
    "sentence_length_mean",
    "sentence_length_median",
    "sent_length_std",
    "syllables_per_token_mean",
    # "syllables_per_token_median",
    "syllables_per_token_std",
    # "n_tokens",
    "n_unique_tokens",
    "prop_unique_tokens",
    # "n_characters",
    "n_sentences",

    # quality
    # "passed_quality_check",
    "n_stop_words",
    "alpha_ratio",
    "mean_word_length",
    # "doc_length",
    "symbol_to_word_ratio_#",
    "proportion_ellipsis",
    "proportion_bullet_points",
    "contains_lorem ipsum",
    "duplicate_line_chr_fraction",
    "duplicate_paragraph_chr_fraction",
    "duplicate_ngram_chr_fraction_5",
    "duplicate_ngram_chr_fraction_6",
    "duplicate_ngram_chr_fraction_7",
    "duplicate_ngram_chr_fraction_8",
    "duplicate_ngram_chr_fraction_9",
    "duplicate_ngram_chr_fraction_10",
    "top_ngram_chr_fraction_2",
    "top_ngram_chr_fraction_3",
    "top_ngram_chr_fraction_4",
    "oov_ratio",

    # dependency_distance
    "dependency_distance_mean",
    "dep_distance_std",
    "prop_adjacent_dependency_relation_mean",
    "prop_adjacent_dependency_relation_std",

    # Readability
    "flesch_reading_ease_en",
    "flesch_reading_ease_de",
    "flesch_reading_ease",
    "flesch_kincaid_grade",
    "gunning_fog",
    "automated_readability_index",
    "coleman_liau_index",
    "lix",
    "rix"

    # POS
    "pos_prop_ADJ",
    "pos_prop_ADP",
    "pos_prop_ADV",
    "pos_prop_CCONJ",
    "pos_prop_DET",
    "pos_prop_NOUN",
    "pos_prop_NUM",
    "pos_prop_PART",
    "pos_prop_PRON",
    "pos_prop_PROPN",
    "pos_prop_PUNCT",
    "pos_prop_SPACE",
    "pos_prop_SYM",
    "pos_prop_VERB",
    "pos_prop_X",
    "pos_prop_AUX",

    # coherence
    "connectives_total",
    "connectives_cap",
    "first_order_coherence",
    "second_order_coherence",

    # morphology
    "shannon_entropy",
    "simpson_diversity",

]

#     features_list = [
#     "alpha_ratio",
#     "automated_readability_index",
#     "coleman_liau_index",
#     "connectives_cap",
#     "connectives",
#     "dependency_distance_mean",
#     "dependency_distance_std",
#     "entropy",
#     "first_order_coherence",
#     "flesch_kincaid_grade",
#     "gunning_fog",
#     "lix",
#     "mean_word_length",
#     "n_stop_words",
#     "n_unique_tokens",
#     "pos_prop_ADP",
#     "pos_prop_ADV",
#     "pos_prop_AUX",
#     "pos_prop_CCONJ",
#     "pos_prop_DET",
#     "pos_prop_NOUN",
#     "pos_prop_PRON",
#     "pos_prop_PUNCT",
#     "pos_prop_VERB",
#     "prop_adjacent_dependency_relation_mean",
#     "proportion_unique_tokens",
#     "second_order_coherence",
#     "sentence_length_mean",
#     "sentence_length_median",
#     "sentence_length_std",
#     "shannon_entropy",
#     "simpson_diversity",
#     "syllables_per_token_mean",
#     "syllables_per_token_std",
#     "token_length_mean",
#     "token_length_median",
#     "token_length_std",
#     "top_ngram_chr_fraction_2"

# ]
